#!/usr/bin/env node
/**
 * docs:verify — proves every documented code snippet.
 *
 * Extracts fenced ```ts / ```typescript blocks from README.md and docs/**\/*.md,
 * writes each to a temp file, and type-checks them all with `tsc --noEmit`
 * against the BUILT package types (dist/index.d.ts). Snippets that are
 * illustrative fragments opt out with an info-string flag: ```ts no-verify.
 *
 * Blocks preceded by `<!-- source: <path>#<region> -->` are also drift-checked
 * against the named `// #region <region>` in that file, so the doc snippet stays
 * a faithful copy of the type-checked example/source.
 *
 * Requires `yarn build` first. Exit non-zero on any type error or drift.
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
  readdirSync,
} from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WORK = join(ROOT, ".docs-verify");
const TSC = join(ROOT, "node_modules", ".bin", "tsc");

if (!existsSync(join(ROOT, "dist", "index.d.ts"))) {
  console.error("dist/index.d.ts not found — run `yarn build` first.");
  process.exit(1);
}

/** Recursively collect markdown files under a dir, excluding generated api/. */
function collectDocs(dir, acc = []) {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, ent.name);
    if (ent.isDirectory()) {
      if (ent.name === "api") continue; // generated by TypeDoc
      collectDocs(p, acc);
    } else if (ent.name.endsWith(".md")) {
      acc.push(p);
    }
  }
  return acc;
}

const docFiles = [join(ROOT, "README.md")];
if (existsSync(join(ROOT, "docs"))) collectDocs(join(ROOT, "docs"), docFiles);

const VERIFY_LANGS = new Set(["ts", "typescript"]);
const fence = /(^|\n)(<!--\s*source:\s*([^\n]+?)\s*-->\s*\n)?```([^\n]*)\n([\s\S]*?)\n```/g;

/** Extract the `// #region <name>` ... `// #endregion` body from a file. */
function extractRegion(filePath, region) {
  const src = readFileSync(filePath, "utf8");
  const lines = src.split("\n");
  const start = lines.findIndex((l) => l.trim() === `// #region ${region}`);
  if (start === -1) return null;
  const end = lines.findIndex(
    (l, i) =>
      i > start &&
      (l.trim() === `// #endregion ${region}` || l.trim() === "// #endregion"),
  );
  if (end === -1) return null;
  return lines.slice(start + 1, end).join("\n");
}

const normalize = (s) =>
  s
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .join("\n")
    .replace(/^\n+|\n+$/g, "");

if (existsSync(WORK)) rmSync(WORK, { recursive: true, force: true });
mkdirSync(WORK, { recursive: true });

writeFileSync(
  join(WORK, "tsconfig.json"),
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        noEmit: true,
        types: ["node"],
        baseUrl: ".",
        paths: {
          "@kaboo/runtime": ["../dist/index.d.ts"],
        },
      },
      include: ["**/*.ts"],
    },
    null,
    2,
  ),
);

const manifest = new Map(); // slug -> "docfile:blockN"
let blocks = 0;
let driftErrors = 0;

for (const file of docFiles) {
  const rel = relative(ROOT, file);
  const content = readFileSync(file, "utf8");
  let m;
  let idx = 0;
  fence.lastIndex = 0;
  while ((m = fence.exec(content)) !== null) {
    const sourceRef = m[3];
    const info = (m[4] || "").trim();
    const code = m[5];
    const [lang, ...flags] = info.split(/\s+/);
    idx++;
    if (!VERIFY_LANGS.has(lang)) continue;
    if (flags.includes("no-verify")) continue;

    // Drift check against a source region, when annotated.
    if (sourceRef) {
      const [srcPath, region] = sourceRef.split("#");
      const abs = join(ROOT, srcPath.trim());
      if (!existsSync(abs)) {
        console.error(`✗ ${rel} block #${idx}: source file not found: ${srcPath}`);
        driftErrors++;
      } else if (!region) {
        console.error(`✗ ${rel} block #${idx}: source marker needs #region`);
        driftErrors++;
      } else {
        const regionBody = extractRegion(abs, region.trim());
        if (regionBody == null) {
          console.error(
            `✗ ${rel} block #${idx}: region "${region}" not found in ${srcPath}`,
          );
          driftErrors++;
        } else if (normalize(regionBody) !== normalize(code)) {
          console.error(
            `✗ ${rel} block #${idx}: drift vs ${srcPath.trim()}#${region.trim()} — regenerate the snippet from the source region.`,
          );
          driftErrors++;
        }
      }
    }

    const slug = `${rel.replace(/[\/\\.]/g, "_")}__${idx}.ts`;
    writeFileSync(join(WORK, slug), code + "\n");
    manifest.set(slug, `${rel} (block #${idx})`);
    blocks++;
  }
}

if (blocks === 0) {
  console.log("No verifiable snippets found.");
  rmSync(WORK, { recursive: true, force: true });
  process.exit(driftErrors > 0 ? 1 : 0);
}

console.log(`Type-checking ${blocks} snippet(s) from ${docFiles.length} file(s)...`);
const res = spawnSync(TSC, ["--noEmit", "-p", join(WORK, "tsconfig.json")], {
  encoding: "utf8",
});
const output = (res.stdout || "") + (res.stderr || "");

let tscFailed = res.status !== 0;
if (tscFailed) {
  // Re-map temp filenames to their originating docs for readable errors.
  let mapped = output;
  for (const [slug, origin] of manifest) {
    mapped = mapped.split(slug).join(`${slug}  [${origin}]`);
  }
  console.error(mapped.trim());
}

rmSync(WORK, { recursive: true, force: true });

if (tscFailed || driftErrors > 0) {
  console.error(
    `\ndocs:verify failed (${driftErrors} drift error(s)${tscFailed ? ", type errors above" : ""}).`,
  );
  process.exit(1);
}
console.log("All documented snippets type-check.");
